

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: sonarsource-build-variables

steps:
  - script: echo Hello!
    displayName: 'Greet the user'
  - task: DownloadSecureFile@1
    displayName: 'Download Maven settings'
    name: mavenSettings
    inputs:
      secureFile: 'maven-settings.xml'
  - bash: >-
      mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy -B --settings $(mavenSettings.secureFilePath) -Denable-repo=qa
      -Dartifact=org.sonarsource.sonarlint.vscode:sonarlint-vscode:3.11.0:vsix -DoutputDirectory=$(Build.SourcesDirectory)/dist
    displayName: ' Download staged vsix'
    env:
      ARTIFACTORY_QA_READER_USERNAME: $(ARTIFACTORY_QA_READER_USERNAME)
      ARTIFACTORY_QA_READER_PASSWORD: $(ARTIFACTORY_QA_READER_PASSWORD)
  - script: npm install
    displayName: 'Install NPM dependencies'
  - script: npm run e2e
    displayName: 'Run tests'
  - publish: ./cypress/videos/welcome.cy.js.mp4
    artifact: ITCaptureScreen_3.11_$(System.JobAttempt)
    condition: always()
  - publish: ./cypress/screenshots/welcome.cy.js/SonarLint Extension -- Should show java error notification (failed).png
    artifact: Screenshot_3.11_$(System.JobAttempt)
    condition: always()
  - publish: ./cypress/screenshots/welcome.cy.js/SonarLint Extension -- Should show SonarLint Explorer Menu Items (failed).png
    artifact: Screenshot_explorermenu_3.11_$(System.JobAttempt)
    condition: always()
  - script: echo Build finished
    displayName: 'Finalize build'
